### PR TITLE
Feature/refactor proc control

### PR DESCRIPTION
**Pull request by alamarre3**
**Warning :** Before creating a pull request, make sure that it does not already exists in the [pull requests](../). Thank you.

## Description
New message for proc control and remove some old AUV7 message

## Fixes
Link all the related issues from the issue tracker
- Closes: #

## How has this been tested ?
(If possible) describe the steps to test these modifications.

## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by supertoto29 — COMMENTED** [review]
@alamarre3 Are we sure that none of the Thruster msg are used in the provider_thruster? Just want to be sure before approuving

**Review by alexemdesgagne — APPROVED** [review]
LGTM

**Comment by alamarre3** [comment]
@supertoto29 Now Thrusters Msg is a unit16[] std msg

**Review by supertoto29 — APPROVED** [review]
LGTM!

**Pull request merged**
